/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{html,ts}",
    ],
    theme: {
        extend: {
            width: {
                '72': '19rem',
                '80': '20rem',
                '160': '40rem'
            },
            colors: {
                'hover-color': 'var(--mat-sys-surface-dim) !important',
                'disabled-color': 'var(--neutral-variant-color-60) !important',
                'success-color': 'var(--success-color-50) !important',
                'warning-color': 'var(--warning-color-50) !important',
                'mat-sys-background': 'var(--mat-sys-background) !important',
                'mat-sys-error': 'var(--mat-sys-error) !important',
                'mat-sys-error-container': 'var(--mat-sys-error-container) !important',
                'mat-sys-inverse-on-surface': 'var(--mat-sys-inverse-on-surface) !important',
                'mat-sys-inverse-primary': 'var(--mat-sys-inverse-primary) !important',
                'mat-sys-inverse-surface': 'var(--mat-sys-inverse-surface) !important',
                'mat-sys-on-background': 'var(--mat-sys-on-background) !important',
                'mat-sys-on-error': 'var(--mat-sys-on-error) !important',
                'mat-sys-on-error-container': 'var(--mat-sys-on-error-container) !important',
                'mat-sys-on-primary': 'var(--mat-sys-on-primary) !important',
                'mat-sys-on-primary-container': 'var(--mat-sys-on-primary-container) !important',
                'mat-sys-on-primary-fixed': 'var(--mat-sys-on-primary-fixed) !important',
                'mat-sys-on-primary-fixed-variant': 'var(--mat-sys-on-primary-fixed-variant) !important',
                'mat-sys-on-secondary': 'var(--mat-sys-on-secondary) !important',
                'mat-sys-on-secondary-container': 'var(--mat-sys-on-secondary-container) !important',
                'mat-sys-on-secondary-fixed': 'var(--mat-sys-on-secondary-fixed) !important',
                'mat-sys-on-secondary-fixed-variant': 'var(--mat-sys-on-secondary-fixed-variant) !important',
                'mat-sys-on-surface': 'var(--mat-sys-on-surface) !important',
                'mat-sys-on-surface-variant': 'var(--mat-sys-on-surface-variant) !important',
                'mat-sys-on-tertiary': 'var(--mat-sys-on-tertiary) !important',
                'mat-sys-on-tertiary-container': 'var(--mat-sys-on-tertiary-container) !important',
                'mat-sys-on-tertiary-fixed': 'var(--mat-sys-on-tertiary-fixed) !important',
                'mat-sys-on-tertiary-fixed-variant': 'var(--mat-sys-on-tertiary-fixed-variant) !important',
                'mat-sys-outline': 'var(--mat-sys-outline) !important',
                'mat-sys-outline-variant': 'var(--mat-sys-outline-variant) !important',
                'mat-sys-primary': 'var(--mat-sys-primary) !important',
                'mat-sys-primary-container': 'var(--mat-sys-primary-container) !important',
                'mat-sys-primary-fixed': 'var(--mat-sys-primary-fixed) !important',
                'mat-sys-primary-fixed-dim': 'var(--mat-sys-primary-fixed-dim) !important',
                'mat-sys-scrim': 'var(--mat-sys-scrim) !important',
                'mat-sys-secondary': 'var(--mat-sys-secondary) !important',
                'mat-sys-secondary-container': 'var(--mat-sys-secondary-container) !important',
                'mat-sys-secondary-fixed': 'var(--mat-sys-secondary-fixed) !important',
                'mat-sys-secondary-fixed-dim': 'var(--mat-sys-secondary-fixed-dim) !important',
                'mat-sys-shadow': 'var(--mat-sys-shadow) !important',
                'mat-sys-surface': 'var(--mat-sys-surface) !important',
                'mat-sys-surface-bright': 'var(--mat-sys-surface-bright) !important',
                'mat-sys-surface-container': 'var(--mat-sys-surface-container) !important',
                'mat-sys-surface-container-high': 'var(--mat-sys-surface-container-high) !important',
                'mat-sys-surface-container-highest': 'var(--mat-sys-surface-container-highest) !important',
                'mat-sys-surface-container-low': 'var(--mat-sys-surface-container-low) !important',
                'mat-sys-surface-container-lowest': 'var(--mat-sys-surface-container-lowest) !important',
                'mat-sys-surface-dim': 'var(--mat-sys-surface-dim) !important',
                'mat-sys-surface-tint': 'var(--mat-sys-surface-tint) !important',
                'mat-sys-surface-variant': 'var(--mat-sys-surface-variant) !important',
                'mat-sys-tertiary': 'var(--mat-sys-tertiary) !important',
                'mat-sys-tertiary-container': 'var(--mat-sys-tertiary-container) !important',
                'mat-sys-tertiary-fixed': 'var(--mat-sys-tertiary-fixed) !important',
                'mat-sys-tertiary-fixed-dim': 'var(--mat-sys-tertiary-fixed-dim) !important',
                'mat-sys-neutral-variant20': 'var(--mat-sys-neutral-variant20) !important',
                'mat-sys-neutral10': 'var(--mat-sys-neutral10) !important',
            }
        }
    },
}

